# Generated by Django 3.0.6 on 2020-05-10 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_finance_api', '0009_auto_20200510_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)])),
                ('primary_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'EURO')], default='INR', max_length=3)),
                ('is_locked', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance_api.OrganizationModel')),
            ],
            options={
                'unique_together': {('month', 'year', 'org')},
                'index_together': {('month', 'year', 'org')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_source', models.CharField(choices=[('Salary', 'Income (Before Taxes)'), ('Rent', 'Rent Received'), ('Interest', 'Interest Received (Before Taxes)'), ('Dividend', 'Dividends Received (Before Taxes)'), ('Redemption', 'Asset Liquidation - Profit/Loss Realized (Before Taxes)'), ('Other', 'Income (Before Taxes)')], default='Salary', max_length=10)),
                ('income_before_tax', models.FloatField(default=0.0)),
                ('tax_withheld', models.FloatField(default=0.0)),
                ('deductions', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'EURO')], default='INR', max_length=3)),
                ('last_updated_on', models.DateField(auto_now_add=True)),
                ('month', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance_api.MemberModel')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance_api.OrganizationModel')),
            ],
            options={
                'index_together': {('member', 'org')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyConverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'EURO')], max_length=3)),
                ('one_dollar_in_currency', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('conversion_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_finance_app.MonthYear')),
            ],
            options={
                'unique_together': {('currency', 'conversion_month')},
                'index_together': {('currency', 'conversion_month')},
            },
        ),
    ]
