# Generated by Django 3.0.6 on 2020-05-11 03:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0009_auto_20200510_0556'),
        ('core_finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_before_tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='org',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='personal_finance_api.OrganizationModel'),
        ),
    ]
