# Generated by Django 3.0.6 on 2020-05-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_finance_app', '0002_auto_20200511_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='member',
            field=models.CharField(choices=[(8, 'Family')], max_length=255),
        ),
    ]
