# Generated by Django 3.0.6 on 2020-05-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0009_auto_20200510_0556'),
        ('core_finance_app', '0004_auto_20200511_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance_api.OrganizationModel'),
        ),
    ]
