# Generated by Django 3.0.6 on 2020-05-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0009_auto_20200510_0556'),
        ('core_finance_app', '0005_auto_20200511_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthyear',
            name='primary_currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'EURO')], default='USD', max_length=3),
        ),
        migrations.AlterIndexTogether(
            name='income',
            index_together={('member', 'org', 'month', 'year')},
        ),
    ]
