# Generated by Django 3.0.6 on 2020-05-12 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0009_auto_20200510_0556'),
        ('core_finance_app', '0006_auto_20200511_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconverter',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal_finance_api.OrganizationModel'),
            preserve_default=False,
        ),
    ]
