# Generated by Django 3.0.6 on 2020-05-12 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_finance_app', '0007_currencyconverter_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyconverter',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='currencyconverter',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AlterUniqueTogether(
            name='currencyconverter',
            unique_together={('currency', 'month', 'year')},
        ),
        migrations.AlterIndexTogether(
            name='currencyconverter',
            index_together={('currency', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='currencyconverter',
            name='conversion_month',
        ),
    ]
