# Generated by Django 3.0.6 on 2020-05-12 05:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0009_auto_20200510_0556'),
        ('core_finance_app', '0009_auto_20200512_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='income',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 5, 2, 8, 664352)),
        ),
        migrations.AlterIndexTogether(
            name='income',
            index_together={('member', 'org', 'month', 'year')},
        ),
    ]
