# Generated by Django 3.0.6 on 2020-05-12 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_finance_app', '0010_auto_20200512_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 5, 4, 43, 375684)),
        ),
    ]
