# Generated by Django 3.0.6 on 2020-05-07 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(default='My Home', max_length=20)),
                ('license_state', models.CharField(choices=[('F', 'Free'), ('T', 'Trial'), ('L', 'Licensed'), ('E', 'Expired'), ('S', 'Shutdown')], default='L', max_length=1)),
                ('license_expiry', models.DateField(default='2024-12-12')),
                ('dashboard_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'EURO')], default='INR', max_length=3)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
