# Generated by Django 3.0.6 on 2020-05-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0002_organizationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance_api.OrganizationModel')),
            ],
            options={
                'unique_together': {('org', 'name')},
                'index_together': {('org', 'name')},
            },
        ),
    ]
