# Generated by Django 3.0.6 on 2020-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0003_membermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='name',
            field=models.CharField(default='Family', max_length=10),
        ),
    ]
