# Generated by Django 3.0.6 on 2020-05-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0004_auto_20200507_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmodel',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='membermodel',
            unique_together=set(),
        ),
    ]
