# Generated by Django 3.0.6 on 2020-05-07 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0005_auto_20200507_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='membermodel',
            unique_together={('org', 'name')},
        ),
    ]
