# Generated by Django 3.0.6 on 2020-05-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0006_auto_20200507_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='is_shutdown',
            field=models.BooleanField(default=False),
        ),
    ]
