# Generated by Django 3.0.6 on 2020-05-09 19:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance_api', '0007_auto_20200509_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='created_on',
            field=models.DateField(default=datetime.date(2020, 5, 9)),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='last_updated_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
